shardingsphere.transaction.seata.at.enable = true
shardingsphere.transaction.seata.tx.timeout = 60

client {
    application.id = order-seata-example
    transaction.service.group = default_tx_group
}
